(define-key h98-mode-map (kbd "C-c C-t") 'hiedb-show-type-h98)
(define-key h98-mode-map (kbd "M-.") 'hiedb-or-tags-goto-def)
(define-key h98-mode-map (kbd "C-c C-r") 'haskell-apply-suggestions)
(define-key h98-mode-map (kbd "C-`") 'haskell-show-compile-buffer)
(define-key h98-mode-map (kbd "C-c C-l") 'h98-reload)
(define-key h98-mode-map (kbd "C-c C-c") 'h98-recomp)
(define-key h98-mode-map (kbd "C-c i") 'haskell-add-import)
(define-key h98-mode-map (kbd "M-.") 'h98-xref-find-definitions)
