(when (eq system-type 'darwin)
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
  (add-to-list 'default-frame-alist '(ns-appearance . dark))
  (setq ns-use-proxy-icon nil)
  (setq frame-title-format nil)
  (setq insert-directory-program "/opt/homebrew/bin/gls" dired-use-ls-dired t)
  (setq dired-listing-switches "-al --group-directories-first"))
